﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace SlashTodo.Infrastructure.Slack
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedISlackApi : ISlackApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedISlackApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<OAuthAccessResponse> OAuthAccess(OAuthAccessRequest request)
        {
            var arguments = new object[] { request };
            return (Task<OAuthAccessResponse>) methodImpls["OAuthAccess"](Client, arguments);
        }

        public virtual Task<AuthTestResponse> AuthTest(AuthTestRequest request)
        {
            var arguments = new object[] { request };
            return (Task<AuthTestResponse>) methodImpls["AuthTest"](Client, arguments);
        }

        public virtual Task<UsersInfoResponse> UsersInfo(UsersInfoRequest request)
        {
            var arguments = new object[] { request };
            return (Task<UsersInfoResponse>) methodImpls["UsersInfo"](Client, arguments);
        }

    }
}


